[package]
name = "dressage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
bitstream-io = "1.2.0"
weezl = "0.1.5"

